version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-commerce
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerce-local
      MYSQL_USER: tiger
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
